POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Title 3",
  "author": "Mike Meyers",
  "url": "thisisaurl3.com",
  "likes": "-12"
}

### Updating Blog
PUT http://localhost:3003/api/blogs/67a1221aa27aab9c5697d477
Content-Type: application/json

{
  "title": "Test Title 4",
  "author": "Kiki",
  "url": "thisisaurl2.com",
  "likes": "100"
}